id: cosplade-1st-stage-debug
title: "CoSplade model – 1st stage (debug)"
description: |
    Debug configuration to test the experimental pipeline.

# We index just a part of the collection to speed up experiments
max_indexed: 10_000
file: experiment

optimization:
    epochs: 4
    validation_interval: 2
    steps_per_epoch: 2
    batch_size: 2

launchers:
    learner: { requirements: duration=12 hours & cuda(mem=8G) }
    splade_indexer: { requirements: duration=6 hours & cuda(mem=24G) * 2 | duration=10 hours & cuda(mem=24G) | duration=12 hours & cuda(mem=8G) }
    splade_retriever: { requirements: duration=12 hours & cuda(mem=8G) & cpu(mem=32G) }
