id: cosplade-1st-stage
title: "CoSPLADE (1st stage)"
description: |
    CoSPLADE (1st stage)
file: experiment

optimization:
    # orConvQA has 31 526 records
    epochs: 128
    steps_per_epoch: 16
    batch_size: 16


launchers:
    learner: { requirements: duration=1 days & cuda(mem=24G) }
    splade_indexer: { requirements: duration=5 days & cuda(mem=24G) * 3 }
    splade_retriever: { requirements: duration=3 days & cuda(mem=8G) & cpu(mem=32G) }
